#!/bin/bash
scriptdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $scriptdir/config
mkdir -p $wpdir 
python $rigdir/redditdl.py $subreddit $wpdir --score $karma --update --num $maxpics >$logfile # download latest $maxpics pics with karma >=$karma
freshpics=$(find $wpdir -type f -mtime -$maxage | wc -l) # get number of up-to-date-pics that would still be there after we delete the the outdated ones

if [ $freshpics > $minpics ]; then # do this only if it will leave us with at least $minpics wallpapers
	find $wpdir -type f -mtime +$maxage -exec rm -rf {} \; # delete all files older that $maxage
	$scriptdir/cycle-wallpapers #set random wallpaper (in case we just deleted the current one)
fi 

